exports.chamillionaire = [
  '               sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  '                +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
  '                 .sNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmNNNNNMMMMMMNMNNMMNNNNNNmmmmddmmmmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN',
  '                  `-hNMMMMMMMMMMMMMMMMMMMMMMMMMMNdhmmmdhhhhdddmNMMMMMMMMNNNNNmmmdhhhhyyhhhdhhhhdmmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNm',
  '                    `:hNMMMMMMMMMMMMMMMMMMMMMMNdyyyyyssssssyysysdmNNMMMNNNNNNmmmmdhddhhhddhyyyyhhhdhhhdddmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMNNmmm',
  '                      `-smMMMMMMMMMMMMMMMMMMMms+/++o+++o+++++++oossydmNNNmmmmNmmmmddddddddhsssyyyhhyyyhhhhddddmmmmNNMMMMMMMMMMMMMMMMMMMNNNNm',
  '                       ``./ymMMMMMMMMMMMMMMNds//////////////++/++oosssydmdmmmmmmdmdddmmmmmhyssyyhhhhhhhhhhdddmddyyyo+ohmNMMMMMMMMMMMMNNmmdmm',
  '                       `````.-/+oNMMMMMMMMNy+/////////+ossyyyssssssyyyhhddmmNNNNmmmmmmNNmmhyyyhhdddddddddhhhddhddddso//:/ydNNMMMMMMMNNNmmmmM',
  '                         ```````.sMMMMMMMNs/:////++shhdmmNNMNNNNNNNNNmmmNNNNNmmmmmmmmmmmdhyyyyhdddmmmmmdddhhdddmNNNmds+::/+/oyhmNMMMMNNmhmNN',
  '                          ``````.:NMMMMMNo/::/+++syyhhhhyhmNNMMNmmNMNMMMMMMMNNmmmmmddddhhyyyyhddmmmmmNNmmmddmmNNNNMMNNmddhhysoo/:/oymMNmhhmN',
  '                          ``````..yMMMMMo:::/++ooosyyyso+++++sshdmmNNMMMNMMMNNNmdddhhhhhhyyyhddmmNNNNNNNNNmmNNNNNNMMMMMMMMMNmhhs//-..:odmhhm',
  '                           ```.-:/smNNMh--:/++ossyyyyyyssoooooossyyhhdddmmNMMmmNddhhhhhhyyyyhhdmNNNNNNNNNNNNNNNNmNNMMMMMMMMMMNmhso/-..``/dNN',
  '                          ```.://++ssyy:--:/+ossyyyyyyssssssossssyyyhhddddddmmmmdddhhdhhhhhhdddmNNNNMMMNNNNNNMNNNNmmmmmmmmmmmmmdyo//-.```.hM',
  '                          ``.+yddyo+oo:--::/+oooooooosossssssssyyhhhdddmmmmdhdmmddddddhhhhhhdddmmNNNNMMNMMNNNNNMMMNNNmmdddhddhyys+//::-.``.m',
  '                           `:hmNmdyoo+----:///////+++++ooosssyyyyhhhdddddddmmmdddddhhhhhhhhhhhddmNNMNNMNNNNNNMNNNMMNNMMMNNNmddhhs/::----.``o',
  '                          ``-hmmdhs++:---:::/:///////++oossyyyyyhhhddddmmddddddddddhhhhhhhhysso+ohmNNNNNNNNMMNNmNMMdmMmNMMMMMNNmdy+-...--.`-',
  '                           ``ommdy+++:---::/:::::::///++osssyyhhhddddddddddddddddddddddhhhhso++:-./yNNNNNNmmmmmmmmmmNNMMMMMMMMMMNmhs:..--.`.',
  '                          ```:dmms//+----::::////////++osyyyyhhhhdddhhhhyyyyhddddhhhhddhhhysso/:-.../yNNNNmmmmmmdddhdddddmmmddNMMMNds----..`',
  '                           ```odd++o+---::::////////+ooosyyyyyyyyyyyyyyyyhhdddddhhhhhhddhhyyoo+/:--...+ydNNmmmmmmddddddhhhys+::sdmNNd+---..`',
  '                          ````-yh+o+/--::::////////++++oosssssssossyhhddhhhhhhhhyyyyhhhhhhyysoo//::--.`.-/ymmmmdddddddddhhyo:-.`./osyo:.....',
  '                          ````./soo//--::////////////++++ooooosyyhddmdsoooossysssssosyyyyyyyyso+///::-.``.-+sydddddhhhhhhyyso/:..`..--..``..',
  '                           ````-++o+:-:::/:///////////+/+++osshdmmmmh+////++ooossooo+oosssssso++///:---.---/:/oydddhhhyyyssso+/:.`````````.-',
  '                           ````./+so:--::://////////////++osyhmmmddds++osssssssysso++oooossoso+/:/:-----++/+///osyhhhhyyysso++/:-``     ``.:',
  '                          `````.:+s+--::://////////+/+++osyhdmdhhhhddyhdNNNNNdhhyyyooooosyyssso+//:::-:--shyo+++++osyyyyyss++/:--``     ``.:',
  '                          `````.:+s/--::://////////+++osyhdmdhyyyyhhddmmNNmmmmNmhhyysssyyyyyyyyyyyyyo++-`.ydhs+/////+oosysso//:-.``    ```.:',
  '                          ````./+oo:--:::///:/:////+osyhdmdhyyyyyyhhhddmmmmmddmmmmddhhhhhhhhhdddddhhhyy+.`-ddhyo+/:://:/osoo/--..``  ````.:y',
  '                         `````.ohho--::://////////+oshddmhyyyyyyhhhhhddddddmmdmmmmNNmmmmmddmmmmmNNNNNmdho:-dddhhs/::::---::/:::-..```````.sd',
  '                          ``..-:sh+-::::////////++oshhddyyyyyyhhhhhdddddmmmmmmmmddmmNNNNNNMNNNNNNNNNNNmdhosmmdddhs/:::--...--::---.````..:dd',
  '                         ````.--:o:-:::://:/://++osyhhhysssyyhhddmmmmNNNNNNNNNNNmmmdmmmmmNNNNNNNNNNmmmdhhhdmmddddho:---......--:--.......sdd',
  '                         `````-+so:::::://::://++oyyhysossshdmmNNNNNNNNNNMMMMMNNNNmmmmmmmmmmmdddmmddhyooo+osdmdddhy/:---.-...-------..../hhm',
  '                         `````./---:://///::://+oosssooosyddmmNNmmmmddddddmmmmmmmmmmmmmmmmmdso+++///::::---:/hmdddh+:--..-..---------..-yhym',
  '                         `````...-::::////:/::/+ooo+++osdmmmdhhysssssyyyyyhhhhhhyyyyhhddmNNmds+++/::---....---ymddho:-......---------.-shssm',
  '                         ````....-::::///://::/++++++oyddhssoo+oosyhhhyyyhhhhhhhyyhhyyssosyhdhyso+/:--........-yddh+:......-----:-----+hsodd',
  '                         ````....-::::://:/:::////++ohyyyo+oooshhdddddddddddhhhhhhdddddhhso/+oyhso+/:-.........-yhs/-......----::----+y++ys/',
  '                         ````....--:::://:::::://+osodhsooooyhddddhhhddddhdhyyhhhhdddddddddhs+/:/+///--....`````-s+:........---------/::+:.`',
  '                         ````....-::::::/::::::::/+sossooooyhdmmhhhddddhyyyyssyhyhdddddddmmmdhs:..::+::-..`..````-:-........------::.-+:-`  ',
  '                         ````....-::::::/::::::://+o+ossydddmmdddmmNmhs+://+:ooosyhhdhdddmmmmmdh+-.-///+/-.```````-..`......--:--::--:--`   ',
  '                         ```.....-/::::://::::::/++ooosyhmNNmmmmmNMMNddhyyy+//://sssohhddddmmmmmds:../ssy+:.```````.......--:::::---:::/`   ',
  '                         ```....:so:::::/:::::::/++++oooshmNmddddmNNmomhhyhmdmNNNmyoosommddddmmmmdh+.-ohdy:--``````....-.--:::::--++/:::.`  ',
  '                         ```..:smMm/:::/:/::::://+++++ooosydmhsoosyyhhhddhs++/ssshdmNNMMMNmdddmmmmdds/ohdy+-:.`````....--:::::::-+y++++-`   ',
  '                        ````.:hNMMMh/////:::::///////+++ooosyhysssssssyyyhhhysyyo//oyyyydmNNNmmmNNmmdyyhdh+//..````..---:::/:::-/ys+++/.    ',
  '                        ````-oMMMMMMy/////::://///////+++oooossyyssoooooosyyyyhhhhshyhysdhhdddNNNNNNNmmmdhyo/-.``...--:::::::---/y+:---.`   ',
  '                       ````..+mMMMMMMh+////://///////++++oooooossyssooooosossssyyssyyyysso++oooyhdmmNMMNmhso+/--...---:::::::--:--.``       ',
  '                      `````..-+mMMMMMMd+/////////+////++ooooooooossssssssssssssssssssyssy+//:-.-..:+/hNmds++:----.---::::::::::.`           ',
  '                      `````....:smMMMMMmo+////+++++++/++oosssssssssyyyyyyyhhhyyyyyyyyhhhys+/--:-.--/:++/+///:--------://::::/ho`            ',
  '                     ``````......:sNMMMMNy+///+ooo+++++oossyyyyyyyyyhhhhhhhhhhhddhhhdddddhys+//::-:-----::/+/:-----::://:::/dMh:.`          ',
  '                     `````........:hMMMMMMdo+++ossooooosyyyyyyyyyyyhhddmmmmddddddddddddddddhyss+o+////:::///+::---::::/:::/dMMmhs/:.```     ',
  '                     `````......-:+yNMMMMMMNyo+ossssssssyyyyyyyyyyhhhdddmmmmmNmmmmddddddddddhhhyyyyooo+///////:::::/:::::/sNMMMNmhys+/:--.``',
  '                    `````..--:/+syyhNMMMMMMMMhsosssssyssyyyyhhhhhhhhdddddddddmmNNNmmmdmddddddhhhhhhysooo++/////::///::::::+NMNNMMNhhhyyysso+',
  '                `````.--:+++ooyyyyhdNMMMMMMMMdyyossssssssyyhhhhhhhdddmmmmmddmmmmmddmdmmmdddddddhdhhysssoo++///////::::/-.-:hMMNNMNhhhhhhhhyy',
  '           ````..-:/+sssssoosyyhhdmMMMMMMMMMMmosyyyyssssssyyhhhhhhhhhddmmmmNNNmmmmmdddddddmmmdddddhyyysoo+++/++//:://:...--yMMNNMNhhhhhhhhhh',
  '````.....--://+oooosyyyysssyyhhhmMMMMMMMMMMMMNsshdysosyyssyyyyyyyyyyyhhhddddmmmNNmmmmmmddmmmddmddhhhyssooo++++//////-.....-omMNNMmhhhhhhhhhh',
  '///+++++++ossssyyyssyyysssyhhdNMMMMMMMMMMMMMMMhsshdhsyyyyyyyssyyhhyhyhhhhdddddmmmmmmmmmmmmmmmmddhhhyyssoooo+//////::-....../dMMMNhhhhhhhhhhh',
  '++ooossoosyyyyyyyyyyyyyyyyhhmMMNNNNMMMMMMMMMMMmyyyyddmddhhdhyyhhdddddddddddddddmdmmmmmmmmmmmdddhhyyyyysso++++++++/::-.....-:smMMdhhhhhhhhhhh',
  'ssssssssyyyhhhhhhyyyyyyhhhhhdMMNNNNMMMMMMMMMMMmyyyyyhmNNNNNmdmmdmmNmmmmNNmmddmdddddhhyhyddhhyyssyssossoo+oosysso+/:---....o++dMmhhhhhhhhhhhh',
  'ysyyyyyyyhhhhhhhhyyyyhhhhhhhhmMMNNMMMMMMMMMMMMdyyyyyyyhmNMMMNNNmNNNNNNNMNNNmmmmmmddhhhyyyyyysooosoooooooyhdhhyso++/:--...:mysmmhhhhhhhhhhhhh',
  'yyyyhhhhhhhhhhhhhyyyhhhhhhhhhhdNMMMMMMMMMMMMNddhyyyyyyyyhmNMMMMMNNMMMMMMMMMMNNNNmmmdhhhyyyssoooosoossyddmdddhyys++::-...-hNh/shhhhhhhhhhhhhh',
  'yyyhhhhhhhhhhhhhyyyhhhhhhhhhhhhhdNMMMMMMMMNmdoohyyyyyyyyyyydmMMMMMMMMMMMMMMMMMNNNNNNmmddhyyyysyyysyddddddddddhyso+/::--:yNNyydhhhhhhhhhhhhhh'
]